/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ku.main;



import com.ku.Common.Encription;
import com.ku.Common.SystemData;
import com.ku.db_connection.DB;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;

/**
 *
 * @author Pubudu Kasun
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        copyRight();
        
         try {
            Image img = ImageIO.read(getClass().getResource("/com/ku/image/grosetup.png"));
            setIconImage(img);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_pass = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        lbl_copyright = new javax.swing.JLabel();
        lbl_design1 = new javax.swing.JLabel();
        txt_cancle = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        lbl_logs = new javax.swing.JLabel();
        lbl_success = new javax.swing.JLabel();
        lbl_detail = new javax.swing.JLabel();
        lbl_pcount = new javax.swing.JLabel();
        txt_username = new com.ku.component.CustomTextField();
        txt_pass = new com.ku.component.customPasswordField();
        customButton1 = new com.ku.component.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ku/image/cancel.png"))); // NOI18N
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 20, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ku/image/maximize (1).png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 6, -1, 20));

        lbl_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ku/image/minimize.png"))); // NOI18N
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Udayanga Log System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Sign In");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        cb_pass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_pass.setForeground(new java.awt.Color(51, 51, 51));
        cb_pass.setText("Show Password");
        cb_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_passActionPerformed(evt);
            }
        });
        jPanel1.add(cb_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 255, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_copyright.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_copyright.setForeground(new java.awt.Color(51, 51, 51));
        lbl_copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_copyright.setText("copy");
        jPanel3.add(lbl_copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 170, -1));

        lbl_design1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_design1.setForeground(new java.awt.Color(51, 51, 51));
        lbl_design1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_design1.setText("jLabel3");
        jPanel3.add(lbl_design1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 420, 40));

        txt_cancle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_cancle.setText("Cancle");
        txt_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cancleActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 40));

        btn_login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        btn_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_loginKeyPressed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 140, 40));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 400, 10));

        lbl_logs.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_logs.setForeground(new java.awt.Color(255, 0, 0));
        lbl_logs.setText("logs");
        jPanel1.add(lbl_logs, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 150, 20));

        lbl_success.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_success.setForeground(new java.awt.Color(0, 204, 51));
        lbl_success.setText("success");
        jPanel1.add(lbl_success, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 150, 20));

        lbl_detail.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_detail.setForeground(new java.awt.Color(102, 102, 255));
        lbl_detail.setText("detail");
        jPanel1.add(lbl_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 293, 110, 20));

        lbl_pcount.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_pcount.setForeground(new java.awt.Color(102, 102, 255));
        lbl_pcount.setText("pcount");
        jPanel1.add(lbl_pcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 293, -1, 20));

        txt_username.setLabelText("User Name");
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 370, 40));

        txt_pass.setLabelText("Password");
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 370, -1));

        customButton1.setText("customButton1");
        jPanel1.add(customButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
         try {
            String username = txt_username.getText();
            String password = new String(txt_pass.getPassword());
            String MD5 = Encription.getMd5(password);
            String sql = "select * from login where username = ? and password = ?";
             Connection con = DB.getNewConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, MD5);
            ResultSet search = ps.executeQuery();
            if (search.next()) {
                    boolean isactive = search.getBoolean("isactive");
                    if (isactive) {
                        
                        SystemData.setCurrentUser(username);
                        SystemData.setUserId(search.getString("id"));
                        
                        lbl_logs.setText(null);
                        lbl_success.setText("Login Successful..");
                        jProgressBar1.setVisible(true);
                        LoadingProgressbar();
                    } else {
                        lbl_logs.setText("This User Inactive..");
                        clearFields();
                    }
            } else {
                lbl_logs.setText("Invalid User Name or Password..");
                clearFields();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
                           
    }//GEN-LAST:event_btn_loginActionPerformed

    private void cb_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_passActionPerformed
          if (cb_pass.isSelected()) {
            txt_pass.setEchoChar((char) 0);
        } else {
            txt_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_passActionPerformed

    private void btn_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loginKeyPressed
       try {
            String username = txt_username.getText();
            String password = new String(txt_pass.getPassword());
            String MD5 = Encription.getMd5(password);
            String sql = "select * from login where username = ? and password = ?";
             Connection con = DB.getNewConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, MD5);
            ResultSet search = ps.executeQuery();
            if (search.next()) {
                    boolean isactive = search.getBoolean("isactive");
                    if (isactive) {
                           SystemData.setCurrentUser(username);
                        SystemData.setUserId(search.getString("id"));
                        
                        lbl_logs.setText(null);
                        lbl_success.setText("Login Successful..");
                        jProgressBar1.setVisible(true);
                        LoadingProgressbar();
                    } else {
                        lbl_logs.setText("This User Inactive..");
                        clearFields();
                    }
            } else {
                lbl_logs.setText("Invalid User Name or Password..");
                clearFields();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_loginKeyPressed

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
       this.setExtendedState(Home.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        txt_pass.grabFocus();
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        btn_login.grabFocus();
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cancleActionPerformed
       txt_username.setText("");
       txt_pass.setText("");
       txt_username.grabFocus();
    }//GEN-LAST:event_txt_cancleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox cb_pass;
    private com.ku.component.CustomButton customButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_design1;
    private javax.swing.JLabel lbl_detail;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_logs;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JLabel lbl_pcount;
    private javax.swing.JLabel lbl_success;
    private javax.swing.JButton txt_cancle;
    private com.ku.component.customPasswordField txt_pass;
    private com.ku.component.CustomTextField txt_username;
    // End of variables declaration//GEN-END:variables
private void LoadingProgressbar() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int i = 0; i < 101; i++) {
                        jProgressBar1.setValue(i);
                        lbl_pcount.setText(i + "%");
                        if (i == 5) {
                            lbl_detail.setText("Database Cheking...");
                            Connection newConnection = DB.getNewConnection();
                            if (newConnection == null) {
                                break;
                            }
                        }
                        if (i >= 50 && i <= 70) {
                            lbl_detail.setText("Database Connected");
                            Thread.sleep(50);
                            continue;
                        }
                        if (i >= 70 && i <= 90) {
                            lbl_detail.setText("Continue...");
                            Thread.sleep(20);
                            continue;
                        }
                        if (i == 100) {
                            Home h = new Home();
                            h.setVisible(true);
                            dispose();
                        }
                        Thread.sleep(20);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        t.start();
    }


  private void clearFields() {
        txt_pass.setText(null);
        txt_username.setText(null);
        cb_pass.setSelected(false);
    }
private void copyRight() {
        lbl_copyright.setText("\u00a9" + "All Rights Reseved");
        lbl_design1.setText("@Design By Pubudu Kasun");
        lbl_pcount.setText(null);
        lbl_success.setText(null);
        lbl_detail.setText(null);
        lbl_logs.setText(null);
        jProgressBar1.setVisible(false);
    }
}
